print("Este programa avalia o resultado das seguintes expressões")
x = float(input("Digite seu primeiro número: "))
y = float(input("Digite seu segundo número: "))
z = float(input("Digite seu terceiro número: "))

print(x > y and y > z)
print(x > y or y > z)
print(x == y or x == z)
print(x != y and y != z)
print(not (x > y) and z > y)
print((x > y and y > z) or (x == z))